### ISSUE TITLE
Support for "array" type 

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#16]
Currently, only the following data types are supported:
**float**, **int**, **string**, and **bool**.

Since we receive activity step details and sleep details from the ring in an array format, we need to add support for arrays as well.

**Comment by AhmedBoutaraa57** [comment]
closed with [commit](https://github.com/mongrov/timon/commit/35649dc2e1f7a3d19fe7281c55b9a8b4ca64813b)
