### ISSUE TITLE
Update Existing Record When Inserting Duplicate Primary Key Value

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#17]
If the date field is unique, the remaining values should still be updated as needed. This is necessary because, for activity metrics, the step count is updated within the same date object over a certain period of time.

For example, if a record with `{date: '2024.10.10 10:10:10', step: 30}` already exists, attempting to insert `{date: '2024.10.10 10:10:10', step: 60} should update the existing record to {date: '2024.10.10 10:10:10', step: 60} 
`

**Comment by AhmedBoutaraa57** [comment]
fixed in this [commit](https://github.com/mongrov/timon/commit/b1b2c326a6a3cad1fb6e072c76943d30a4ab6417)
