### ISSUE TITLE
Incorrect Storage of Integer Values in Schema Fields Defined as int

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#18]
When certain fields in the schema are defined as int|float and others as int only, an issue occurs where values inserted into fields defined strictly as int are incorrectly stored as 0.

For example, consider the following schema for activitydetails:
```
{
  "date": {
    "type": "string",
    "required": true,
    "unique": true
  },
  "distance": {
    "type": "int|float"
  },
  "step": {
    "type": "int|float"
  },
  "calories": {
    "type": "int|float"
  },
  "arraySteps": {
    "type": "array"
  }
}
```

If step is set to accept only int values, trying to update the field with a value like 39 results in it being recorded and retrieved as 0 instead.

**Comment by AhmedBoutaraa57** [comment]
I tried different things but couldn't reproduce! I need more input about this one

**Comment by RoshanNepal3** [comment]
Seems like the issue was from the app's side. Closing it for now.
