### ISSUE TITLE
Query not working when using "startTime_SleepData" as primary key

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#19]
When there is schema with primary key other than “date”, query is not working correctly:

For example, if we have “startTime_SleepData” as a primary key that works as “date”. 

`“SELECT * FROM sleep WHERE startTime_SleepData BETWEEN '${start}' AND '${end}' ORDER BY startTime_SleepData desc”`

It is returning empty.   

However, if we just do, “SELECT * FROM sleep” all the data are returned

`[{"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.09 02:37:04", "totalSleepTime": 41}, {"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.09 00:36:04", "totalSleepTime": 107}, {"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.08 22:36:01", "totalSleepTime": 120}, {"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.08 02:05:03", "totalSleepTime": 47}, {"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.08 00:05:01", "totalSleepTime": 120}, {"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.07 22:05:01", "totalSleepTime": 120}]`

Using the same query with date works for other metrics: 
 `"SELECT * FROM spo2 WHERE date BETWEEN '${start}' AND '${end}' ORDER BY date desc" `

**Comment by AhmedBoutaraa57** [comment]
the problem has to do with case sensitivity, if we can rename the field to `starttime_sleepdata` that should solve the issue

**Comment by RoshanNepal3** [comment]
We cannot rename the field. That is how data comes from the ring. 

`[{"arraySleepQuality": [Array], "sleepUnitLength": 1, "startTime_SleepData": "2024.11.09 02:37:04", "totalSleepTime": 41}]`

**Comment by AhmedBoutaraa57** [comment]
some databases and query engines don't allow special characters like underscores or mixed-case names unless wrapped in quotes

**Comment by RoshanNepal3** [comment]
Query is working correctly if we wrap the key with quotations. 

For example: 
`SELECT * FROM ${collection} WHERE "${SLEEP_PRIMARY_KEY}" BETWEEN '${start}' AND '${end}' ORDER BY "${SLEEP_PRIMARY_KEY}" ${sort}`
