### ISSUE TITLE
Handle DELETE and other necessary queries

### ISSUE THREAD

**Issue by RoshanNepal3** [mongrov/timon#20]
**Expected**
The following method should delete all the records from the specific table
```
   await query('timon', {
          start: '2024-01-01',
          end: '2024-11-14',
        }, `DELETE FROM timon_table`);
```

**Current Behaviour:** 
Does not delete any record.

**Comment by AhmedBoutaraa57** [comment]
[datafusion query engine](https://datafusion.apache.org/user-guide/sql/index.html) does not support DELETE sql queries.
once we are clear on the use case we can introduce a new API for drop tables
